import test from "node:test";
import assert from "node:assert/strict";
import { APEX_CONTRACTS, APEX_MAP_IDS, apexPhaseDividers, apexPhaseForRatio, orderedApexTargets, validateApexContracts } from "../apex-encounters.js";
import { Simulation } from "../engine.js";
test("apex registry strictly covers every map with authored phases",()=>{assert.deepEqual(Object.keys(APEX_CONTRACTS).sort(),[...APEX_MAP_IDS].sort());assert.deepEqual(validateApexContracts(),[]);for(const contract of Object.values(APEX_CONTRACTS)){assert.ok(Object.isFrozen(contract));assert.ok(contract.phases.length>=2);assert.ok(new Set(contract.phases.flatMap(p=>p.intentCycle)).size>=3);assert.deepEqual(apexPhaseDividers(contract).map(x=>x.position),[contract.phaseGateRatio]);}});
test("phase lookup changes at the exact authored gate",()=>{for(const contract of Object.values(APEX_CONTRACTS)){assert.equal(apexPhaseForRatio(contract,contract.phaseGateRatio+Number.EPSILON).index,0);assert.equal(apexPhaseForRatio(contract,contract.phaseGateRatio).index,1);assert.equal(apexPhaseForRatio(contract,0).index,1);}});
test("target ordering is stable across input order and ties",()=>{const origin={x:0,y:0},players=[{id:"later",replaySlot:2,x:10,y:0},{id:"first",replaySlot:0,x:-10,y:0},{id:"down",replaySlot:1,x:1,y:0,downed:true}];assert.deepEqual(orderedApexTargets(origin,players,2).map(x=>x.id),["first","later"]);assert.deepEqual(orderedApexTargets(origin,[...players].reverse(),2).map(x=>x.id),["first","later"]);});

test("all four maps spawn versioned apex state and acquire locked geometry",()=>{for(const map of APEX_MAP_IDS){const sim=new Simulation({map,players:[{id:"p",name:"P",specialist:"zuri",replaySlot:0}]});sim.spawnBoss();const boss=sim.enemies.find(e=>e.boss);boss.apexReadyTick=sim.tick;sim.updateBoss(boss,1/60,sim.players);assert.equal(boss.apexContractId,APEX_CONTRACTS[map].id);assert.equal(boss.apexActionState,"windup");assert.ok(boss.apexGeometry);const frozen=JSON.stringify(boss.apexGeometry);sim.players[0].x+=400;sim.updateBoss(boss,1/60,sim.players);assert.equal(JSON.stringify(boss.apexGeometry),frozen);}});

test("the phase gate clamps overkill once, never heals, and recovery preserves intent",()=>{const sim=new Simulation({map:"beachhead",players:[{id:"p",name:"P",specialist:"zuri",replaySlot:0}]});sim.spawnBoss();const boss=sim.enemies.find(e=>e.boss),gate=boss.maxHp*APEX_CONTRACTS.beachhead.phaseGateRatio;boss.apexReadyTick=sim.tick;sim.updateBoss(boss,1/60,sim.players);sim.damageEnemy(boss,boss.maxHp,"p",true,"test");assert.equal(boss.hp,gate);assert.equal(boss.apexPendingPhase,1);sim.updateBoss(boss,1/60,sim.players);assert.equal(boss.hp,gate);assert.equal(boss.apexPhaseIndex,1);assert.equal(boss.apexActionState,"transition");const restored=Simulation.fromRecoveryState(sim.exportRecoveryState());assert.equal(restored.enemies.find(e=>e.boss).hp,gate);assert.equal(restored.enemies.find(e=>e.boss).apexPhaseIndex,1);});

test("recovery rejects malformed apex geometry instead of trusting reconnect state",()=>{const sim=new Simulation({map:"warehouse",players:[{id:"p",name:"P",specialist:"zuri",replaySlot:0}]});sim.spawnBoss();const boss=sim.enemies.find(e=>e.boss);boss.apexReadyTick=sim.tick;sim.updateBoss(boss,1/60,sim.players);const recovery=sim.exportRecoveryState(),stored=recovery.lists.enemies.find(e=>e.boss);stored.apexGeometry.originX=Number.NaN;assert.throws(()=>Simulation.fromRecoveryState(recovery),/invalid geometry|non-finite/);});
