#!/usr/bin/env python3
"""Build deterministic, pixel-exact collision masks from environment atlases."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "assets" / "environment-chunks"
OUTPUT = ROOT / "environment-collision-masks.js"
MAP_IDS = ("warehouse", "outskirts", "lab", "beachhead")
ALPHA_THRESHOLD = 16


def row_runs(alpha: Image.Image) -> list[list[int]]:
    pixels = alpha.load()
    rows: list[list[int]] = []
    for y in range(alpha.height):
        runs: list[int] = []
        start = -1
        for x in range(alpha.width):
            solid = pixels[x, y] >= ALPHA_THRESHOLD
            if solid and start < 0:
                start = x
            elif not solid and start >= 0:
                runs.extend((start, x))
                start = -1
        if start >= 0:
            runs.extend((start, alpha.width))
        rows.append(runs)
    return rows


def frame_mask(alpha: Image.Image) -> dict:
    bounds = alpha.point(lambda value: 255 if value >= ALPHA_THRESHOLD else 0).getbbox()
    if bounds is None:
        raise ValueError("Environment frame has no visible alpha")
    return {
        "width": alpha.width,
        "height": alpha.height,
        "bounds": list(bounds),
        "rows": row_runs(alpha),
    }


def build_payload() -> dict:
    maps = {}
    sources = {}
    for map_id in MAP_IDS:
        path = ASSET_DIR / f"{map_id}-atlas.webp"
        raw = path.read_bytes()
        atlas = Image.open(path).convert("RGBA")
        if atlas.width % 2 or atlas.height % 2:
            raise ValueError(f"{path.name}: atlas dimensions must divide into a 2x2 grid")
        frame_width, frame_height = atlas.width // 2, atlas.height // 2
        frames = []
        for index in range(4):
            left = (index % 2) * frame_width
            top = (index // 2) * frame_height
            frames.append(frame_mask(atlas.crop((left, top, left + frame_width, top + frame_height)).getchannel("A")))
        maps[map_id] = {"frames": frames}
        sources[map_id] = {"path": f"assets/environment-chunks/{path.name}", "sha256": hashlib.sha256(raw).hexdigest()}
    return {
        "schema": "lastlight.environment-alpha-collision.v1",
        "alphaThreshold": ALPHA_THRESHOLD,
        "atlas": {"columns": 2, "rows": 2},
        "sources": sources,
        "maps": maps,
    }


def render_module(payload: dict) -> str:
    encoded = json.dumps(payload, separators=(",", ":"), sort_keys=True)
    return (
        "// Generated by tooling/build_environment_collision_masks.py. Do not hand-edit.\n"
        "export const ENVIRONMENT_COLLISION_MASKS = " + encoded + ";\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in module is stale")
    args = parser.parse_args()
    rendered = render_module(build_payload())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"stale collision mask module: {OUTPUT}")
            return 1
        print(f"verified {OUTPUT}")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT} ({len(rendered.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
