import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { assertCombatOrientationAudit, buildCombatOrientationAudit } from "../combat-orientation-audit.js";

export function combatOrientationAuditHtml(report) {
  const payload = JSON.stringify(report).replaceAll("<", "\\u003c");
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lastlight combat orientation audit</title><style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#02070d;color:#f5f1e8}*{box-sizing:border-box}body{margin:0;padding:28px;background:radial-gradient(circle at 50% -20%,#173046,#02070d 50%)}main{max-width:1180px;margin:auto}.eyebrow{color:#69e6d2;font-size:12px;font-weight:900;letter-spacing:.16em}h1{font-size:30px;margin:7px 0}.sub{color:#8ea6ba;margin:0 0 20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{border:1px solid #294156;background:#07121deb;padding:15px}.name{font-weight:900;text-transform:uppercase;letter-spacing:.08em}.stage{position:relative;height:150px;margin:12px 0;background:#030a11;border:1px solid #183047;overflow:hidden}.actor{position:absolute;left:50%;top:50%;width:32px;height:32px;margin:-16px;border:2px solid #69e6d2;transform:rotate(45deg)}.arrow{position:absolute;left:50%;top:50%;height:3px;width:58px;transform-origin:0 50%}.arrow:after{content:'';position:absolute;right:-1px;top:-4px;border-left:9px solid currentColor;border-top:5px solid transparent;border-bottom:5px solid transparent}.pointer{background:#ff667d;color:#ff667d}.auto{background:#f6d56b;color:#f6d56b}.commit{background:#69e6d2;color:#69e6d2;height:4px}.muzzle{position:absolute;width:8px;height:8px;margin:-4px;border-radius:50%;background:#fff4cb;box-shadow:0 0 12px #ff8b5f}.checks{display:grid;grid-template-columns:1fr 1fr;gap:5px;font-size:11px;color:#a9bbca}.ok{color:#69e6d2}.legend{display:flex;gap:18px;color:#9cb0c0;font-size:12px;margin:14px 0}.legend i{display:inline-block;width:12px;height:3px;margin-right:5px;vertical-align:3px}@media(max-width:800px){.grid{grid-template-columns:1fr}}
</style></head><body><main><div class="eyebrow">AUTHORITATIVE MOTION QA</div><h1>Combat orientation audit</h1><p class="sub">Nine specialists · pointer, auto-target, committed shot, strafe language, and muzzle alignment · ${report.metadataSha256.slice(0,16)}</p><div class="legend"><span><i style="background:#ff667d"></i>pointer</span><span><i style="background:#f6d56b"></i>auto target</span><span><i style="background:#69e6d2"></i>committed body</span></div><section class="grid" id="grid"></section></main><script>
const report=${payload},grid=document.querySelector('#grid');for(const c of report.cases){const card=document.createElement('article');card.className='card';const arrow=(kind,a)=>'<i class="arrow '+kind+'" style="transform:rotate('+a+'rad)"></i>';card.innerHTML='<div class="name">'+c.specialist+'</div><div class="stage"><i class="actor"></i>'+arrow('pointer',c.pointerFacing)+arrow('auto',c.autoFacing)+arrow('commit',c.committedFacing)+'<i class="muzzle" style="left:calc(50% + '+c.muzzle.x+'px);top:calc(50% + '+c.muzzle.y+'px)"></i></div><div class="checks"><span class="ok">✓ sticky target</span><span class="ok">✓ meaningful switch</span><span class="ok">✓ '+c.movementMode+'</span><span class="ok">✓ body-neutral safe</span><span class="ok">✓ muzzle origin</span><span class="ok">✓ '+c.combatSourceId+'</span></div>';grid.append(card)}
</script></body></html>`;
}

const report = buildCombatOrientationAudit(), errors = assertCombatOrientationAudit(report), command = process.argv[2] || "verify";
if (errors.length) { for (const error of errors) console.error(error); process.exitCode = 1; }
else if (command === "report") { const out = resolve("artifacts", "combat-orientation-audit"); mkdirSync(out, { recursive: true }); writeFileSync(resolve(out, "metadata.json"), `${JSON.stringify(report, null, 2)}\n`); writeFileSync(resolve(out, "index.html"), combatOrientationAuditHtml(report)); process.stdout.write(`${out}\n`); }
else if (command === "verify") process.stdout.write(`verified ${report.coverage.checks} combat-orientation checks - ${report.metadataSha256}\n`);
else { console.error("usage: node tooling/run_combat_orientation_audit.js [verify|report]"); process.exitCode = 2; }
